### Ljung-Box test for no autocorrelation

In [144]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [203]:
from TimeSeries import *
r0=[1]
phi=[0,0.99]
rt=ARModel(phi,r0,100,0.01)
rt1=MAModel(1.0,[.00],10000,1.0)

In [204]:
from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.tsa.stattools import adfuller
rslt=acorr_ljungbox(rt,lags=10,boxpierce=True)
rslt1=acorr_ljungbox(rt1,lags=10,boxpierce=True)
rslt_stat=adfuller(rt)

In [205]:
print rslt_stat

(-1.7974229862999695, 0.3817418579009082, 2L, 97L, {'5%': -2.8918307730370025, '1%': -3.4996365338407074, '10%': -2.5829283377617176}, -551.9937228435399)


In [207]:
with open('test.txt','r') as ifile:
    y=[]
    for line in ifile:
        y.append(float(line))

In [209]:
y=np.asarray(y)

In [211]:
res=y-y.mean()

In [214]:
acorr_ljungbox(res,lags=[5,10,15],boxpierce=True)

(array([ 19.36044047,  30.59859933,  36.96393946]),
 array([ 0.00164647,  0.00068328,  0.00128095]),
 array([ 18.24358711,  27.60952685,  32.32439481]),
 array([ 0.00265612,  0.00208406,  0.00581414]))